name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Docker image
        run: docker build -t prometheus-demo .
      - name: Run container
        run: docker run -d -p 5000:5000 prometheus-demo
